# Generated by Django 2.1.3 on 2018-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20181112_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.FileField(default=1, upload_to='imagem_func'),
            preserve_default=False,
        ),
    ]
